### ISSUE TITLE
Telegram.Bot包使用了有BUG的版本，新申请的机器人无法使用该功能

### ISSUE THREAD

**Issue by chenxuuu** [xpnas/inotify#13]
## 版本

发布版docker

## 现象

调用接口显示成功，实际未成功发送

## 复现方式

配置一个tg发送的消息类型（已检查bottoken格式正确，手动使用curl无问题）

## 日志

```log
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Invalid format. A valid token looks like "1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy". (Parameter 'token')
   at Telegram.Bot.TelegramBotClient..ctor(String token, HttpClient httpClient)
   at Inotify.Sends.Products.TelegramBotSendTemplate.SendMessage(SendMessage message) in /src/Inotify/Sends/Products/TelegramBotSendTemplate.cs:line 29
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Inotify.Sends.SendTaskManager.SendWork(Thread thread) in /src/Inotify/Sends/SendTaskManager.cs:line 179
   at Inotify.Sends.SendTaskManager.<>c__DisplayClass12_0.<Run>b__0(Object e) in /src/Inotify/Sends/SendTaskManager.cs:line 85
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

## 后台设置截图

![图片](https://user-images.githubusercontent.com/10357394/198185851-dae72b80-95e0-47e5-8cb6-7c1576b7c2d9.png)

**Comment by chenxuuu** [comment]
知道原因了，你用的是有问题的`Telegram.Bot`版本，botid使用的是`int`，然而现在申请的bot编号均已超过0x7fffffff，所以报错认为格式不合法了

https://github.com/TelegramBots/Telegram.Bot/blob/v15/src/Telegram.Bot/TelegramBotClient.cs#L32-L33

升级一下`Telegram.Bot`包的版本吧？

https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/TelegramBotClient.cs#L31-L32

**Comment by xpnas** [comment]
谢谢，已升级到最新版本18.0.0
