### ISSUE TITLE
稳定版报错

### ISSUE THREAD

**Issue by github-amazingboy** [xpnas/inotify#3]
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15

Unhandled exception. System.TypeInitializationException: The type initializer for 'Inotify.Sends.SendCacheStore' threw an exception.

---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: systemInfo'.

at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()

at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.ExecuteReader()

at NPoco.Database.<>c__DisplayClass298_0.<ExecuteReaderHelper>b__0()

at NPoco.Database.ExecutionHook[T](Func`1 action)

at NPoco.Database.ExecuteReaderHelper(DbCommand cmd)

at NPoco.Database.ExecuteDataReader(DbCommand cmd, Boolean sync)

at NPoco.AsyncHelper.RunSync[T](Task`1 task)

at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql, PocoData pocoData)+MoveNext()

at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

at NPoco.Linq.QueryProvider`1.ToList()

at Inotify.Sends.SendCacheStore..cctor() in /src/Inotify/Sends/SendCacheStore.cs:line 19

--- End of inner exception stack trace ---

at Inotify.Sends.SendCacheStore.GetSystemValue(String key) in /src/Inotify/Sends/SendCacheStore.cs:line 41

at Inotify.Sends.SendTaskManager.Run() in /src/Inotify/Sends/SendTaskManager.cs:line 80

at Inotify.Program.Main(String[] args) in /src/Inotify/Program.cs:line 15
```

**Comment by xpnas** [comment]
全新安装，还是旧版本升级出现的？

**Comment by xpnas** [comment]
@github-amazingboy 已更新，如果已部署，请升级镜像
